inputs:
  repo:
    required: true
    type: string
  branch:
    required: true
    type: string
    default: "main"

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: https://gitea.com/actions/checkout@v4
      with:
        repository: "${{ inputs.repo }}"
        ref: "${{ inputs.branch }}"
        path: repo

    - name: Configure container
      id: init
      run: |
        repository="${{ inputs.repo }}"
        echo "repo=${repository##*/}" >> "$GITEA_ENV"
        
        cd repo
        for env in container{.env,.local.env,${{ gitea.repository_owner }}.env}; do [[ -f "$env" ]] && source "$env" || true; done
        [[ "${{ gitea.repository_owner }}" == "stage" && -f container.stage.env ]] && source container.stage.env
        echo "ip=$IP" >> $GITEA_ENV
        echo "id=$ID" >> $GITEA_ENV
        echo "cores=$CORES" >> $GITEA_ENV
        echo "memory=$MEMORY" >> $GITEA_ENV
        echo "swap=$SWAP" >> $GITEA_ENV
        echo "disk=$DISK" >> $GITEA_ENV
        echo "boot=$BOOT" >> $GITEA_ENV
        echo "mount=$MOUNT" >> $GITEA_ENV
      shell: bash

    - name: Base configuration
      uses: main/base/.gitea/workflows@main
      with:
        ip: ${{ env.ip }}
        id: ${{ env.id }}
        hostname: ${{ env.repo }}
        cores: ${{ env.cores }}
        memory: ${{ env.memory }}
        swap: ${{ env.swap }}
        disk: ${{ env.disk }}
        boot: ${{ env.boot }}
        mount: ${{ env.mount }}
      if: ${{ gitea.ref == 'refs/heads/release' }}

    - name: Checkout repository
      uses: https://gitea.com/actions/checkout@v4
      with:
        repository: "${{ inputs.repo }}"
        ref: "${{ inputs.branch }}"
        path: "${{ env.repo }}"

    - name: Checkout libraries
      uses: https://gitea.com/actions/checkout@v4
      with:
        repository: 'main/libraries'
        ref: 'main'
        path: "${{ env.repo }}/libraries"

    - name: Create Snapshot
      if: ${{ inputs.branch == 'snapshot' }}
      run: echo "Utils.snapshot(self, node['snapshot']['data'])" > "${{ env.repo }}/recipes/default.rb"
      shell: bash

    - name: Configure container
      run: |
        tar -c "${{ env.repo }}" -cz | ssh -o StrictHostKeyChecking=no -i "/share/.ssh/${{ env.id }}" "config@${{ env.ip }}" 'sudo tar xz -C /tmp
          sudo -E IP=${{ env.ip }} ID=${{ env.id }} HOST=${{ vars.HOST }} LOGIN=${{ vars.LOGIN }} PASSWORD=${{ vars.PASSWORD }} PWD="$(pwd)" \
            cinc-client --local-mode $CONFIG_ARGS --config-option cookbook_path="/tmp" -o "${{ env.repo }}"'
      shell: bash
