inputs:
  repo:
    required: true
    type: string
  ref:
    required: true
    type: string
    default: "main"

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: https://gitea.com/actions/checkout@v4
      with:
        repository: "${{ inputs.repo }}"
        ref: "${{ inputs.ref }}"
        path: repo

    - name: Configure container
      id: init
      run: |
        source repo/config.env
        echo "ip=$IP" >> $GITEA_ENV
        echo "id=$ID" >> $GITEA_ENV
        echo "hostname=$HOSTNAME" >> $GITEA_ENV
        echo "cores=$CORES" >> $GITEA_ENV
        echo "memory=$MEMORY" >> $GITEA_ENV
        echo "swap=$SWAP" >> $GITEA_ENV
        echo "disk=$DISK" >> $GITEA_ENV
        echo "boot=$BOOT" >> $GITEA_ENV
        echo "mount=$MOUNT" >> $GITEA_ENV
      shell: bash

    - name: Base configuration
      uses: main/base/.gitea/workflows@main
      with:
        ip: ${{ env.ip }}
        id: ${{ env.id }}
        hostname: ${{ env.hostname }}
        cores: ${{ env.cores }}
        memory: ${{ env.memory }}
        swap: ${{ env.swap }}
        disk: ${{ env.disk }}
        boot: ${{ env.boot }}
        mount: ${{ env.mount }}
      if: ${{ gitea.ref == 'refs/heads/release' }}

    - name: Checkout repository
      uses: https://gitea.com/actions/checkout@v4
      with:
        repository: "${{ inputs.repo }}"
        ref: "${{ gitea.ref_name }}"
        path: repo

    - name: Checkout libraries
      uses: https://gitea.com/actions/checkout@v4
      with:
        repository: 'main/libraries'
        ref: 'main'
        path: 'repo/libraries'

    - name: Configure container
      run: |
        tar -c repo -cz . | ssh -o StrictHostKeyChecking=no -i "/share/.ssh/${id}" "config@${ip}" 'sudo tar xz -C /tmp
          sudo -E IP=${{ env.ip }} ID=${{ env.id }} HOST=${{ vars.HOST }} LOGIN=${{ vars.LOGIN }} PASSWORD=${{ vars.PASSWORD }} PWD="$(pwd)" \
            cinc-client --local-mode $CONFIG_ARGS --config-option cookbook_path="/tmp" -o repo'
      shell: bash




