- name: SSH configuration
  notify: Restart SSH
  when: (configure_ssh | default(true) | bool)
  block:
    - name: Disable SSH password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"
        backup: yes
        state: present

    - name: Disable SSH root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"
        backup: yes
        state: present

- name: Container accessibility
  block:
    - name: Store container key
      ansible.builtin.set_fact:
        private_key: "{{ private_key ~ (private_key.endswith('\n') | ternary('', '\n')) }}"
        public_key: "{{ public_key ~ (public_key.endswith('\n') | ternary('', '\n')) }}"

    - name: Save container keys
      copy:
        content: "{{ item.content }}"
        dest: "{{ key_dir }}/{{ item.name }}"
        owner: app
        group: config
        mode: "{{ item.mode }}"
      loop:
        - { name: "{{ id }}", content: "{{ private_key }}", mode: "0600" }
        - { name: "{{ id }}.pub", content: "{{ public_key }}",  mode: "0644" }

    - name: Verify container key
      shell: "ssh-keygen -y -f {{ key_dir }}/{{ id }} | diff - {{ key_dir }}/{{ id }}.pub"
      register: verify
      changed_when: false
      failed_when: verify.rc != 0

    - name: Set container authorized key
      ansible.posix.authorized_key:
        user: "{{ item }}"
        key: "{{ public_key }}"
        state: present
        exclusive: no
      loop: "{{ ssh_users }}"

- name: Ensure files and directories
  include_tasks: state.yml
  vars:
    defaults:
      - { path: "/app/.ssh/authorized_keys", state: "file", mode: "0750", owner: "config", group: "config" }
