- name: User defaults
  block:

  - name: Set environment
    copy:
      src: environment
      dest: /etc/environment
      owner: root
      group: root
      mode: '0644'

  - name: Generate locales
    community.general.locale_gen:
      name: "{{ item }}"
      state: present
    loop:
      - en_US.UTF-8

  - name: Set locale
    copy:
      src: locale
      dest: /etc/default/locale
      owner: root
      group: root
      mode: '0644'

  - name: Set profile
    copy:
      src: profile.sh
      dest: /etc/profile.d/10-profile.sh
      owner: root
      group: root
      mode: '0644'

  - name: User
    block:
      - name: Set root bashrc
        copy:
          dest: /root/.bashrc
          content: |
            for f in /etc/profile.d/*.sh; do
              . "$f"
            done
          owner: root
          group: root
          mode: '0644'

  - name: Timezone
    block:

      - name: Timezone file
        ansible.builtin.lineinfile:
          path: /etc/timezone
          create: yes
          line: 'Europe/Berlin'

      - name: Timezone link
        ansible.builtin.file:
          src: /usr/share/zoneinfo/Europe/Berlin
          dest: /etc/localtime
          state: link
          force: yes

      - name: Configure timezone
        ansible.builtin.command: dpkg-reconfigure -f noninteractive tzdata
