- name: User defaults
  block:

  - name: Set environment
    copy:
      src: environment
      dest: /etc/environment
      owner: root
      group: root
      mode: '0644'

  - name: Set profile
    copy:
      src: profile.sh
      dest: /etc/profile.d/10-profile.sh
      owner: root
      group: root
      mode: '0644'

  - name: User
    block:
      - name: Set root bashrc
        copy:
          dest: /root/.bashrc
          content: |
            for f in /etc/profile.d/*.sh; do
              . "$f"
            done
          owner: root
          group: root
          mode: '0644'