- name: Base container configuration
  block:
    - name: Set key directory
      set_fact:
        key_dir: "{{ KEYS_DIR | default('/share/.ssh') }}"

    - name: Update system
      apt:
        update_cache: true
        upgrade: full
        cache_valid_time: 3600
        autoclean: true
        autoremove: true

    - name: Install default applications
      apt:
        name: "{{ default_packages }}"
        state: present

    - name: Create default groups
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ default_groups }}"

    - name: Create default users
      user:
        name: "{{ item.name }}"
        shell: "{{ item.shell | default('/bin/bash') }}"
        groups: "{{ item.groups | default(omit) }}"
        create_home: "{{ item.create_home | default(true) }}"
        home: "{{ item.home | default(omit) }}"
        state: present
      loop: "{{ default_users }}"
      register: created_users

    - name: Configure Sudo
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ item }}"
        regexp: "^#?{{ item }}"
        line: "{{ item }} ALL=(ALL:ALL) NOPASSWD: ALL"
        validate: 'visudo -cf %s'
        owner: root
        group: root
        mode: '0440'
        state: present
        create: yes
      loop: "{{ ssh_users }}"

- name: Ensure files and directories
  include_tasks: state.yml
  vars:
    extra:
      - { path: "/app", state: "directory", mode: "0755", owner: "app", group: "config" }
      - { path: "/app/.ssh", state: "directory", mode: "0711", owner: "app", group: "config" }

- name: Container accessibility
  import_tasks: access.yml

- name: Configuration management
  import_tasks: tools.yml

- name: User default settings
  import_tasks: defaults.yml
