- name: Set files and directories
  set_fact:
    defaults:
      - { path: "{{ DIR_KEYS }}", state: "directory", mode: "0711", owner: "app", group: "config" }
      - { path: "{{ DIR_CERTS }}", state: "directory", mode: "0711", owner: "app", group: "config" }
      - { path: "/app", state: "directory", mode: "0755", owner: "app", group: "config" }
      - { path: "/app/.ssh", state: "directory", mode: "0711", owner: "app", group: "config" }

- name: Ensure directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ defaults }}"
  when: item.state == 'directory'

- name: Ensure files
  file:
    path: "{{ item.item.path }}"
    state: file
    owner: "{{ item.item.owner }}"
    group: "{{ item.item.group }}"
    mode: "{{ item.item.mode }}"
  loop: "{{ defaults }}"
  when: item.state == 'file'

- name: Find keys
  find:
    paths: "{{ DIR_KEYS }}"
    file_type: file
  register: keys

- name: Set key permissions
  file:
    path: "{{ item.path }}"
    state: file
    owner: "app"
    group: "config"
    mode: "{{ '0644' if item.path.endswith('.pub') else '0600' }}"
  loop: "{{ keys.files }}"
  loop_control:
    label: "{{ item.path }}"
