- name: Install configuration management
  block:
    - name: Get configuration management versions
      ansible.builtin.uri:
        url: https://downloads.cinc.sh/files/stable/cinc/
        return_content: yes
      register: download_configuration_management_version
      until: download_configuration_management_version.status == 200
      changed_when: false

    - name: Sort configuration management versions
      ansible.builtin.set_fact:
        versions: "{{ (download_configuration_management_version.content | regex_findall('href=\"(\\d+\\.\\d+\\.\\d+)/\"') | sort | reverse)[:3] }}"

    - name: Download latest configuration management
      ansible.builtin.get_url:
        url: "https://downloads.cinc.sh/files/stable/cinc/{{ item }}/debian/13/cinc_{{ item }}-1_{{ arch | default('amd64') }}.deb"
        dest: /tmp/cinc.deb
      register: download_result
      until: download_result is succeeded
      ignore_errors: true
      loop: "{{ versions }}"
      loop_control:
        loop_var: item

    - name: Install configuration management
      ansible.builtin.apt:
        deb: /tmp/cinc.deb
        state: present
