---
- name: "Base Container"
  hosts: localhost
  gather_facts: no
  vars:
    dir:       "{{ (lookup('env', 'DIR')      | default('') | trim) or '/tmp/config' }}"
    share_dir: "{{ (lookup('env', 'SHARE')    | default('') | trim) or '/share' }}"
    storage:   "{{ (lookup('env', 'STORAGE')  | default('') | trim) or 'local:vztmpl' }}"
    template:  "{{ (lookup('env', 'TEMPLATE') | default('') | trim) or 'debian-13-standard_13.1-2' }}"
    cert_dir:  "{{ share_dir }}/.cert"
    key_dir:   "{{ share_dir }}/.ssh"
  tasks:

    - name: Ensure directories
      file:
        path: "{{ key_dir }}"
        state: directory
      loop: ["{{ share_dir }}", "{{ cert_dir }}", "{{ key_dir }}"]

    - name: Generate container key on host
      community.crypto.openssh_keypair:
        path: "{{ key_dir }}/{{ id }}"
        type: ed25519
        force: false

    - name: Container
      ansible.builtin.include_role:
        name: container

- name: Remote container configuration
  hosts: container
  gather_facts: yes
  become: true
  tasks:
    - name: Copy share if exists
      ansible.builtin.copy:
        src: /share/
        dest: /share/
        remote_src: no
        mode: "0775"
        force: no
      when: share | default(false) | bool

    - name: Apply base configuration
      ansible.builtin.include_role:
        name: base
      tags: base

    - name: Configure mounts
      ansible.builtin.include_role:
        name: mount
      vars:
        host: "{{ lookup('env', 'HOST') }}"
        login: "{{ lookup('env', 'LOGIN') }}"
        password: "{{ lookup('env', 'PASSWORD') }}"
        mount: "{{ mount }}"
      when:
        - lookup('env','PROXMOX_PASSWORD') | default('', True) | length > 0
        - not (share | default(false) | bool)
        - mount is defined
      tags: mounts
