---
- name: "Base Container"
  hosts: localhost
  gather_facts: no
  vars:
    os: "{{ OS | default('local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst') }}"
    key_dir: "{{ KEYS_DIR | default('/share/.ssh') }}"
  tasks:
    - name: Ensure key directory
      file:
        path: "{{ key_dir }}"
        state: directory

    - name: Generate container key on host
      community.crypto.openssh_keypair:
        path: "{{ key_dir }}/{{ id }}"
        type: ed25519
        force: false

    - name: Check container configuration
      ansible.builtin.stat:
        path: "config.json"
      register: config_file

    - name: Load container configuration
      ansible.builtin.include_vars:
        file: "config.json"
        name: config
      when: config_file.stat.exists

    - name: Set Proxmox configuration
      ansible.builtin.set_fact:
        PROXMOX_HOST: "{{ lookup('env', 'PROXMOX_HOST') }}"
        PROXMOX_USER: "{{ lookup('env', 'PROXMOX_USER') }}"
        PROXMOX_PASSWORD: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
        PROXMOX_TOKEN: "{{ lookup('env', 'PROXMOX_TOKEN') }}"
        PROXMOX_SECRET: "{{ lookup('env', 'PROXMOX_SECRET') }}"
      when:
        - (config_file.stat.exists and config.proxmox is defined) or (not config_file.stat.exists)

    - name: Container
      ansible.builtin.include_role:
        name: container

- name: Remote container configuration
  hosts: container
  gather_facts: yes
  become: true
  tasks:
    - name: Apply base configuration
      ansible.builtin.include_role:
        name: base
      tags: base

    - name: Configure mounts
      ansible.builtin.include_role:
        name: mount
      vars:
        host: "{{ lookup('env', 'HOST') }}"
        login: "{{ lookup('env', 'LOGIN') }}"
        password: "{{ lookup('env', 'PASSWORD') }}"
        mount: "{{ mount }}"
      when:
        - not (share | default(false) | bool)
        - mount is defined
      tags: mounts
