---
- name: "Base Container"
  hosts: localhost
  gather_facts: no
  vars:
    BASE_DIR:       "{{ (lookup('env', 'BASE_DIR') }}"
    BASE_STORAGE:   "{{ (lookup('env', 'BASE_STORAGE') }}"
    BASE_TEMPLATE:  "{{ (lookup('env', 'BASE_TEMPLATE') }}"
    DIR_SHARE:      "{{ (lookup('env', 'BASE_SHARE') }}"
    DIR_CERTS:      "{{ (lookup('env', 'BASE_SHARE') }}/.cert"
    DIR_KEYS:       "{{ (lookup('env', 'BASE_SHARE') }}/.ssh"
  tasks:

    - name: Ensure directories
      file:
        path: "{{ DIR_KEYS }}"
        state: directory
      loop: ["{{ DIR_SHARE }}", "{{ DIR_CERTS }}", "{{ DIR_KEYS }}"]

    - name: Generate container key on host
      community.crypto.openssh_keypair:
        path: "{{ DIR_KEYS }}/{{ id }}"
        type: ed25519
        force: false

    - name: Container
      ansible.builtin.include_role:
        name: container

- name: Remote container configuration
  hosts: container
  gather_facts: yes
  become: true
  tasks:
    - name: Copy share if exists
      ansible.builtin.copy:
        src: /share/
        dest: "{{ DIR_SHARE }}"
        remote_src: no
        mode: "0775"
        force: no
      when: share | default(false) | bool

    - name: Apply base configuration
      ansible.builtin.include_role:
        name: base
      tags: base

    - name: Configure mounts
      ansible.builtin.include_role:
        name: mount
      vars:
        host: "{{ lookup('env', 'HOST') }}"
        login: "{{ lookup('env', 'LOGIN') }}"
        password: "{{ lookup('env', 'PASSWORD') }}"
        mount: "{{ mount }}"
      when:
        - lookup('env','PROXMOX_PASSWORD') | default('', True) | length > 0
        - not (share | default(false) | bool)
        - mount is defined
      tags: mounts
